name: Build and deploy JAR app to Azure Web App - billora-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # =========================
  # BUILD
  # =========================
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven

      - name: Build with Maven
        working-directory: ./billora-backend
        run: mvn clean package -DskipTests

      # Rename the generated JAR to a fixed name
      - name: Prepare JAR
        working-directory: ./billora-backend
        run: |
          JAR_FILE=$(find target -maxdepth 1 -type f -name "*.jar" ! -name "*-plain.jar" | head -n 1)
          echo "Found JAR: $JAR_FILE"
          cp "$JAR_FILE" billora-backend.jar
          ls -lh billora-backend.jar

      # Upload fixed JAR
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ./billora-backend/billora-backend.jar


  # =========================
  # DEPLOY
  # =========================
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ./artifact

      # Verify downloaded file
      - name: Verify artifact
        run: |
          echo "Downloaded files:"
          ls -lah ./artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DECA12DC323D4E3291CA80085377BADB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BE859B005A654E87AD5BD60B411F08A0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3332E71036D14FF78198EB16F8CFAFD5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'billora-backend'
          slot-name: 'Production'
          package: './artifact/billora-backend.jar'
